### ISSUE TITLE
License copyright information

### ISSUE THREAD

**Issue by fcooper8472** [rajeshrinet/pystokes#1]
@rajeshrinet just checking the license for the purpose of the JOSS review.

I see that the [copyright information](https://github.com/rajeshrinet/pystokes/blob/ce4e718590dba339f9a8d49dfcdbdc84f9c6e8e7/LICENSE#L3) is Rajesh Singh, and this may be completely correct.  I just wanted to double check this, and that it should not be an institution?  (For instance, I know that at Oxford I do not own the copyright to projects I work on.)

**Comment by rajeshrinet** [comment]
@fcooper8472 thanks very much for pointing this out. I have now contacted my department to seek advice on this. I will update the copyright information accordingly. I would would also like to note that we have been working on this repo since 2014, while I moved to Cambridge in 2018. 

I am also adding my coauthor @ronojoy of the JOSS submission to bring him in the conversation.

**Comment by rajeshrinet** [comment]
@fcooper8472 the file [LICENSE](https://github.com/rajeshrinet/pystokes/blob/master/LICENSE) has now been updated appropriately. Thanks for your suggestion.

**Comment by fcooper8472** [comment]
Perfect!
